# config/settings.py
import os

API_KEY = os.getenv('API_KEY_SPOT_BINANCE')
API_SECRET = os.getenv('API_SECRET_SPOT_BINANCE')
BASE_URL = 'https://api.binance.com/api'
TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
TELEGRAM_GROUP_ID = os.getenv('TELEGRAM_GROUP_ID')
SYMBOLS = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT']
INTERVAL = '1m'
CACHE_LIFETIME = 300  # 5 menit
MAX_RETRIES = 5
RETRY_BACKOFF = 1  # 1 detik
BUY_MULTIPLIER = 0.925
SELL_MULTIPLIER = 1.03
TOLERANCE = 0.01
